info:
    title: resource_huaweicloud_aom_cmdb_environment
    description: Manages an AOM environment resource within HuaweiCloud.
host: myhuaweicloud.com
tags:
    - name: AOM
servers:
    - url: https://aom.cn-east-3.myhuaweicloud.com
paths:
    /v1/environments:
        POST:
            tag: AOM
            operationId: CreateEnvironment
            x-ref-api: POST /v1/environments
    /v1/environments/{id}:
        DELETE:
            tag: AOM
            operationId: DeleteEnvironment
            x-ref-api: DELETE /v1/environments/{id}
        GET:
            tag: AOM
            operationId: GetEnvironment
            x-ref-api: GET /v1/environments/{id}
        PUT:
            tag: AOM
            operationId: UpdateEnvironment
            x-ref-api: PUT /v1/environments/{id}
