info:
    title: resource_huaweicloud_css_configuration
    description: Manages a CSS configuration resource within HuaweiCloud.
host: myhuaweicloud.com
tags:
    - name: CSS
servers:
    - url: https://dws.myhuaweicloud.com
paths:
    /v1.0/{project_id}/clusters/{cluster_id}/ymls/update:
        POST:
            tag: CSS
            operationId: CreateConfiguration
            x-ref-api: POST /v1.0/{project_id}/clusters/{cluster_id}/ymls/update
    /v1.0/{project_id}/clusters/{id}/ymls/joblists:
        GET:
            tag: CSS
            operationId: CreateConfigurationWaiting
            x-ref-api: GET /v1.0/{project_id}/clusters/{id}/ymls/joblists
    /v1.0/{project_id}/clusters/{id}/ymls/template:
        GET:
            tag: CSS
            operationId: GetConfiguration
            x-ref-api: GET /v1.0/{project_id}/clusters/{id}/ymls/template
    /v1.0/{project_id}/clusters/{id}/ymls/update:
        POST:
            tag: CSS
            operationId: DeleteConfiguration
            x-ref-api: POST /v1.0/{project_id}/clusters/{id}/ymls/update
